import type { NextConfig } from 'next'

const isProd = process.env.NODE_ENV === 'production'

const nextConfig: NextConfig = {
  output: 'export',
  basePath: isProd ? '/kerbside-auto' : '',
  assetPrefix: isProd ? '/kerbside-auto/' : '',
  env: {
    NEXT_PUBLIC_BASE_PATH: isProd ? '/kerbside-auto' : '',
  },
  images: {
    // Static export: derivatives are pre-generated by scripts/images-build.mjs.
    unoptimized: true,
  },
}

export default nextConfig
